#define DEBUG_FLAG 0
#define RAW_DATA_FLAG 0

#define PIN_LED1_OUT_SDI 4
#define PIN_LED1_OUT_CKI 5
#define PIN_LED2_OUT_SDI 6
#define PIN_LED2_OUT_CKI 7
#define PIN_LED3_OUT_SDI 8
#define PIN_LED3_OUT_CKI 9
#define PIN_LED4_OUT_SDI 10
#define PIN_LED4_OUT_CKI 11
#define PIN_LED5_OUT_SDI 12
#define PIN_LED5_OUT_CKI 13

#define PIN_IR_IN 13
#define PIN_MIC_IN A0
#define IR_AUDIO 0

#define NUM_LEDS 32
#define NUM_LED_STRIPS_SLAVE 5
#define NUM_LED_STRIPS_MASTER 4
#define NUM_LED_STRIPS 5 //For Compatability
#define SLAVE_ADDRESS 1

#define EVENT_DETECT_HUMAN_VOICE 1




